### ISSUE TITLE
Existing users and spaces in Names issues

### ISSUE THREAD

**Issue by john-henry** [bhashkar007/userinitialsphoto#1]
Nice plugin.

I was already through a build with existing users when I installed plugin so had to fiddle with `$event->isNew` to get this to work for them. It would be nice to have a setting or a config file to switch this.

The other thing is the First name. My first name I would consider `John Henry` Henry isn't my second name. Plugin falls over when I add my first name becasue of space

`https://ui-avatars.com/api/John Henry+Donovan/128/843b62/fff/2/0.5/1/1.png`

It would help if there was some URI encoding like the following on the name strings

`https://ui-avatars.com/api/John%20Henry+Donovan/128/843b62/fff/2/0.5/1/1.png`

**Comment by hashtagerrors** [comment]
I have updated the plugin which adds a setting page. When `Assign Images to New User Only` is unchecked, photos will be assigned to old users too.

NOTE: When updating plugin from `v1.0.0` to `v1.1.0` you must have to do a `composer remove hashtagerrors/hashtagerror/user-initials-photo` and then `composer require hashtagerror/user-initials-photo` to get plugin setting and section page.
