### ISSUE TITLE
Account doesn't get activated

### ISSUE THREAD

**Issue by arifje** [bhashkar007/userinitialsphoto#3]
So we have been running this plugin for more than a week and the last few days we were  getting more and more complaints from users that they couldn't activate their account. 

After doing some tests if appears that there's an issue with the plugin: when it's enabled it prevents people from activating their account. The activation email is received, clicked and they are redirect to our welcome/success template. But, the user isn't logged in (autoLoginAfterAccountActivation = enabled in config) and the account is still pending.

Disabling the plugin fixes the issue for new registrations. But the problem now is that we have hundreds of pending accounts. We've tried resending the activation email to the pending users, but the accounts won't get activated after clicking the link. Second time the link is clicked is tells them the key is invalid and they should try logging in or reset their passwords.

Any help is appreciated.

Craft CMS 3.1.23
PHP 7.2

**Comment by arifje** [comment]
Quick update; as it appears accounts created with this plugin activated are missing the **unverifiedEmail** value, which is NULL. This is why the accounts can't be activated.

When the plugin is disabled all new accounts have a valid **unverifiedEmail** value.

**Comment by hashtagerrors** [comment]
I don't get any issues while activating user accounts with this plugin. But I am going to do a thorough check using plugin in different projects and revert you back ASAP.

**Comment by hashtagerrors** [comment]
Linking the same issue posted on craft cms by you for visitors to get a detailed understanding : [Account activation issues #4165](https://github.com/craftcms/cms/issues/4165)
