### ISSUE TITLE
How to get to plugin page?

### ISSUE THREAD

**Issue by chasegiunta** [bhashkar007/userinitialsphoto#5]
How is one supposed to navigate to the plugin's page where you Assign Photos to all users?

**Comment by hashtagerrors** [comment]
In version above 1.1.0 , it should be in the Dashboard's left sidebar.

**Comment by chasegiunta** [comment]
Interesting. I'm on 1.1.1 and it's not showing in the sidebar. I was able to navigate to it directly but unsure why it wouldn't be showing.

**Comment by hashtagerrors** [comment]
v1.0.0 didn't have plugin section page and settings and therefore composer.json had `"hasCpSettings": false` in it. In v1.1.0 plugin section page and settings were added and so composer.json was also updated to have `"hasCpSettings": true`. But when a plugin is updated from Craft or even through `composer update` . Craft's `plugin.php` doesn't update `hasCpSettings` value. This is only updated when a `composer remove` and `composer require` is done. This may be a reason why you aren't seeing the plugin page.

**Comment by chasegiunta** [comment]
I think `hasCpSection` is the culprit. I'm able to get to the Settings page just fine.

https://github.com/hashtagerrors/userinitialsphoto/blob/5b3366a1905363b30df8da5770be2ec9f85a4ac1/composer.json#L36

**Comment by hashtagerrors** [comment]
Fixed in `v1.1.2`

**Comment by ghost** [comment]
A push of 1.1.2 to Packagist would be nice though :)
